language: csharp
solution: AppverseMVC/AppverseMVC.sln
script:
  - xbuild /p:Configuration=Debug AppverseMVC.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - cd AppverseMVC
  - nuget restore AppverseMVC.sln

